import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAZwyNROy
bi0+hyxNAC8/GPAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIGDAY0bcbSUZ/Dlb
SSdHZwHaTNHnGvLrC05d8JkfFUldAAAAkK6LcTCD/7fzWRsVFe3H5OSlfV9Htj0HnOJHT1
0VCVuHq2KjtAhF63ymmUTWixPQ0eBrxhKiXf3/mW3zyxaR3LpEIrAPA/DvPtMJp2mI6ZrH
zIFUrtELIdQA2yT/b/D7oxflIX3EZYeD7HJV+UofMjcx1ckaXYUIkc8Suy0l7bNcHWevgf
S394pOwhOaysGs/g==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
