import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDEbxCPtr
SSSSWfrj07xdoRAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIAXFooVD+evtnObj
yHIANs57IG5wP6SZ2qjb0BdJlA7+AAAAkHoac2jZYD03QDmGw5QmQ1lfQMzTAX6wDK5GfK
Lz58vhl7GjNtmmpIpRtVr4+PGLoaEaXJXofYzw1n6gXTCGNU8MSIG6vdyNHTNuaAadOQYj
rOAiw3F2Xh5INGRHDV9D55jeXSiibqyjhHpk1+s1DTdjCkNYDYc1FJ9lcUXOaGTXMqKPps
6H/z1Q1p2O4gjJXg==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
